### PR TITLE
fix: better error messages

### PR DESCRIPTION
**Pull request by ffMathy**
- [X] I have added automatic tests where applicable
- [X] The PR title is suitable as a release note
- [X] The PR contains a description of what has been changed
- [X] The description contains manual test instructions

## Changes
I was trying to use the awesome and brand new Schema Generator (https://github.com/ftrackhq/ftrack-ts-schema-generator).

However, I got the following error:

```
Failed to perform request.  CustomError [ServerError]: fetch failed
    at Session.getErrorFromResponse (/Users/Documents/src/ftrack-javascript/source/session.ts:336:19)
    at Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:561:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:534:5)
    at async Session.query (/Users/Documents/src/ftrack-javascript/source/session.ts:738:23) {
  errorCode: undefined
}
Server reported error in unexpected format.  CustomError [ServerError]: fetch failed
    at Session.getErrorFromResponse (/Users/Documents/src/ftrack-javascript/source/session.ts:336:19)
    at Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:561:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:534:5)
    at async Session.query (/Users/Documents/src/ftrack-javascript/source/session.ts:738:23) {
  errorCode: undefined
}
/Users/Documents/src/ftrack-javascript/source/session.ts:336
    const error = new ErrorClass(response.content, response.error_code);
                  ^
CustomError [ServerError]: fetch failed
    at Session.getErrorFromResponse (/Users/Documents/src/ftrack-javascript/source/session.ts:336:19)
    at Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:588:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:534:5)
    at async Session.query (/Users/Documents/src/ftrack-javascript/source/session.ts:738:23) {
  errorCode: undefined
}
```

This wasn't very useful, so I made this pull request. After that pull request, the error was instead way more helpful:

```
Failed to perform request.  CustomError [ServerError]: Error: unable to verify the first certificate
    at Session.getErrorFromResponse (/Users/Documents/src/ftrack-javascript/source/session.ts:336:19)
    at Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:561:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:534:5)
    at async Session.query (/Users/Documents/src/ftrack-javascript/source/session.ts:738:23) {
  errorCode: undefined
}
Server reported error in unexpected format.  CustomError [ServerError]: Error: unable to verify the first certificate
    at Session.getErrorFromResponse (/Users/Documents/src/ftrack-javascript/source/session.ts:336:19)
    at Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:561:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:534:5)
    at async Session.query (/Users/Documents/src/ftrack-javascript/source/session.ts:738:23) {
  errorCode: undefined
}
/Users/Documents/src/ftrack-javascript/source/session.ts:336
    const error = new ErrorClass(response.content, response.error_code);
                  ^
CustomError [ServerError]: Error: unable to verify the first certificate
    at Session.getErrorFromResponse (/Users/Documents/src/ftrack-javascript/source/session.ts:336:19)
    at Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:588:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Session.call (/Users/Documents/src/ftrack-javascript/source/session.ts:534:5)
    at async Session.query (/Users/Documents/src/ftrack-javascript/source/session.ts:738:23) {
  errorCode: undefined
}
```

This allowed me to truly figure out that it was a company-related VPN thing that caused the issue, and that I needed some certificate changes.

## Test
I tried the following test - it provides a much better error message now:

```typescript
import { Session } from '@ftrack/api';

const client = new Session();
client.query("select id from Project").then(console.log);
```

### CODE REVIEW

**Review by gismya — COMMENTED** [review]
Could it be beneficial to include both the message and the cause?

**Comment by ffMathy** [comment]
Yes - I'll fix that Monday. But feel free to add it already! 😄

**Comment by ffMathy** [comment]
@gismya actually, I remember now why I didn't do it. I tried it at first, but the cause also seems to include the message and/or the stack trace?

I do at least remember that the error looked duplicated when I included both. 

Not sure if that's still what we want. But up to you! 🙏

**Review by gismya — APPROVED** [review]

**Comment by gismya** [comment]
I just hadn't approved the new release - should be out now.

**Pull request merged**
