### PR TITLE
Experiment/event hub for node #1

### PR DESCRIPTION
**Pull request by ffMathy**
- [ ] I have added automatic tests where applicable
- [ ] The PR title is suitable as a release note
- [ ] The PR contains a description of what has been changed
- [ ] The description contains manual test instructions

### CODE REVIEW

**Comment by gismya** [comment]
Spent a few hours on this yesterday, and you've identified the most likely candidate for working. The earlier ones are not compatible with modern node, and the newer ones aren't compatible with the server socket.io-version. The issues you've been seeing are probably unrelated to the corporate VPN you are using. I couldn't nail down exactly why it's not working - the next step will probably be to use Fiddler or Wireshark to inspect the data sent by the two different implementations and see where they differ to nail down any changes we need to do. I will also compare and make sure the version of 0.9 we are currently distributing within the repository is unchanged, and doesn't contain any custom changes.

I will try to make some time for that, but if you get there before that, please share the findings.

**Comment by ffMathy** [comment]
@gismya awesome - thanks for the progress update! Unfortunately, I don't think I can justify spending much more of the company's time on this.

It would have to be my spare time, which is a bit scarce these days. But I'll do my best - it just might take a long time before I get some time to do it.

So if you intend to keep pursuing this, that would be our dream scenario!

**Comment by gismya** [comment]
I did more investigations of this issue, and have concluded that the differences between the data format of socket.io 0.9 and v1.x is too large to make this a viable option. I'm closing this PR but will continue to look into alternate ways of doing this.

**Comment by ffMathy** [comment]
Okay. That's unfortunate, but also good to be able to narrow down options in a way.

Keep us posted! 🙏

**Pull request closed without merging**
