### PR TITLE
fix: documentation building

### PR DESCRIPTION
**Pull request by hdd**
- [ ] I have added automatic tests where applicable
- [x] The PR title is suitable as a release note
- [x] The PR contains a description of what has been changed
- [ ] The description contains manual test instructions

You can locally test the doc builds with:

python setup.py build_sphinx

### CODE REVIEW

**Review by jimmycallin — CHANGES_REQUESTED** [review]
does the docs build require a package.json version being set? unfortunately we cannot do that, as version is set dynamically during release process to make sure we don't have to commit anything during the release process.

**Comment by lucaas** [comment]
I thought the plan was to remove JS API Client docs from readthedocs and replace it. See previous discussion in slack: https://ftrack.slack.com/archives/CGGQ3220K/p1664445614338179

> does the docs build require a package.json version being set?

We can remove the dependency:

* https://github.com/ftrackhq/ftrack-javascript/blob/main/setup.py#L16:L22
* https://github.com/ftrackhq/ftrack-javascript/blob/main/doc/conf.py#L41:L46 

I don't think we have an alternative we could use - so we would need to leave this as something generic. The git tag is only available if we build on GitHub.

**Comment by jimmycallin** [comment]
> I thought the plan was to remove JS API Client docs from readthedocs and replace it. See previous discussion in slack: https://ftrack.slack.com/archives/CGGQ3220K/p1664445614338179
> 
> > does the docs build require a package.json version being set?
> 
> We can remove the dependency:
> 
> * https://github.com/ftrackhq/ftrack-javascript/blob/main/setup.py#L16:L22
> * https://github.com/ftrackhq/ftrack-javascript/blob/main/doc/conf.py#L41:L46
> 
> I don't think we have an alternative we could use - so we would need to leave this as something generic. The git tag is only available if we build on GitHub.

Yes, that's on my todo list. Maybe we should just do that now while working on the api, instead of maintaining the old documentaiton.

**Comment by seebergs** [comment]
Should look into the docs as part of this if possible (or asap) since users are currently being pointed to outdated docs at https://ftrack-javascript-api.rtd.ftrack.com/en/stable/ from various places (which in turn refers to Bitbucket).

**Comment by lucaas** [comment]
> https://ftrack-javascript-api.rtd.ftrack.com

Points to readthedocs.io, which is what Lorenzo was trying to build I guess. I would redirect that page to this repo (until we have new documentation), but couldn't find a good way of doing so. Here is some more info: https://github.com/readthedocs/readthedocs.org/issues/2267

**Comment by hdd** [comment]
@lucaas yes, that's correct.
This PR is to allow the docs to keep on building on readthedocs, mostly because is currently out of date.
Happy to ditch this PR if there's any better plans for the docs though !

**Pull request closed without merging**
